version: 2

models:
    - name: fact_orders
      description: "Tabela Fato de Pedidos"
      columns:
        - name: order_id
          description: "Coluna de Chave Primária"
          tests:
            - unique
            - not_null
    
    - name: dim_customers
      description: "Tabela Dimensão de Clientes"
      columns:
        - name: customer_id
          description: "Coluna de Chave Primária"
          tests:
            - unique
            - not_null